spring.application.name=assets-manager

# Azure Blob Storage Configuration
blob.storage.endpoint=https://yourstorageaccount.blob.core.windows.net
blob.container.name=your-container-name

# Max file size for uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Azure Service Bus Configuration
spring.cloud.azure.servicebus.namespace=${SERVICE_BUS_NAMESPACE}
spring.cloud.azure.servicebus.entity-type=queue
spring.cloud.azure.servicebus.processor.auto-complete=false

# Database Configuration
# 1. Do not set spring.datasource.password, access token will be retrieved automatically and used as password.
# 2. For system-assigned managed identity only, "spring.cloud.azure.credential.client-id" can be omitted.
# 3. For service principal auth, remove "spring.cloud.azure.credential.managed-identity-enabled" property and add these properties:
#   spring.cloud.azure.profile.tenant-id=<your-service-principal-tenant-id>
#   spring.cloud.azure.credential.client-id=<your-service-principal-client-id>
#   spring.cloud.azure.credential.client-secret=<your-service-principal-client-secret>
# 4. For Azure sovereign clouds, set the following two properties (the "azure" cloud type is the default and can be omitted):
#   spring.cloud.azure.profile.cloud-type=azure_china / azure_germany / azure_us_government / azure
#   spring.datasource.azure.scopes=<scope-for-your-cloud>
#     azure_china: https://ossrdbms-aad.database.chinacloudapi.cn/.default
#     azure_germany: https://ossrdbms-aad.database.cloudapi.de/.default
#     azure_us_government: https://ossrdbms-aad.database.usgovcloudapi.net/.default
#     azure: https://ossrdbms-aad.database.windows.net/.default
# 5. Remember to set the values for the environment variables in the URL below
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_SERVER}.postgresql.database.azure.com:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}?sslMode=REQUIRED
spring.datasource.username=${MANAGED_IDENTITY_NAME}
spring.datasource.azure.passwordless-enabled=true
spring.cloud.azure.credential.client-id=<your_managed_identity_client_id>
spring.cloud.azure.credential.managed-identity-enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true